# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "release/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Build, Push, and Deploy"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Version Number
        id: version
        run: echo ::set-output name=semver::$(echo ${{github.ref}} | rev | cut -d "/" -f 1 | rev)

      - name: Docker Login
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: https://ghcr.io
          username: DotJoshJohnson
          password: ${{github.token}}
          logout: true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{github.workspace}}
          file: ${{github.workspace}}/eng/band-account-manager.dockerfile
          push: true
          tags: |
            ghcr.io/laurelschooldistrict/band-account-manager:latest
            ghcr.io/laurelschooldistrict/band-account-manager:${{steps.version.outputs.semver}}

      - name: Install doctl
        uses: digitalocean/action-doctl@d36a87b1d9c7bd55c8d8434ff2a991a6ee32a448
        with:
          token: ${{secrets.DIGITALOCEAN_TOKEN}}

      - name: Save kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 readynext-nyc1-prod

      - name: Interpolate Kubernetes Manifests
        uses: cschleiden/replace-tokens@121d9153eda2951d490e9f724a67ff095ab4c4f7
        with:
          files: ${{github.workspace}}/eng/kubernetes/*.yml
        env:
          RUN_ID: ${{github.run_id}}
          VERSION: ${{steps.version.outputs.semver}}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f ${{github.workspace}}/eng/kubernetes -n laurelschooldistrict

      - name: Verify Deployment
        run: kubectl rollout status deployment/band-account-manager -n laurelschooldistrict
